import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Header from '@/components/header'
import { useState } from 'react'
import lidzbarskiginza from '../lidzbarskiginza'


const inter = Inter({ subsets: ['latin'] })

export default function Ginza() {

  const [ language, setLanguage ] = useState(0);
  const [ page, setPage ] = useState(0);
  const text = lidzbarskiginza;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-col text-center items-center bg-gradient-to-br min-h-screen h-full bg-gradient-to-br from-amber-50 to-amber-50 via-stone-50">
        <div className='p-2 pt-12 m-2 font-bold text-violet-900 text-xl lg:text-3xl'>
          <h3>Ginza Rabba</h3>
          <p>ࡂࡉࡍࡆࡀ ࡓࡁࡀ</p>
          <div className='flex flex-col p-2 text-sm'>
            <button onClick={() => setLanguage(0)}>
              <p className='p-2 bg-white bg-opacity-10 hover:bg-opacity-70 rounded-xl transition-all'>🇺🇸 English (Translation)</p>
            </button>
            <button onClick={() => setLanguage(1)}>
              <p className='p-2 bg-white bg-opacity-10 hover:bg-opacity-70 rounded-xl transition-all'>🇩🇪 Deutsch (Lidzbarski)</p>
            </button>
          </div>
        </div>
        <div>
              <div className='p-2 m-2 bg-violet-100 text-black rounded-xl'>
                {language == 0 &&
                  <div>
                    <h3 className='text-2xl lg:text-4xl font-bold uppercase p-4 m-4'>{lidzbarskiginza[0].title}</h3>
                    <h3 className='text-xl lg:text-3xl font-bold uppercase p-2 m-2'>{lidzbarskiginza[0].subtitle}</h3>
                    <p className='text-sm uppercase'>or</p>
                    <h3 className='text-xl lg:text-3xl font-bold uppercase p-2 m-2'>{lidzbarskiginza[0].subtitle2}</h3>
                    <p className='text-sm uppercase'>translated and explained</p>
                    <p className='text-sm uppercase'>by</p>
                    <h3 className='text-xl lg:text-3xl font-bold uppercase p-2 m-2'>{lidzbarskiginza[0].author}</h3>
                    <div className='flex flex-row flex-wrap text-center items-center justify-center p-2 m-2'>
                      <div className='flex flex-col p-2 m-2 text-xs uppercase'>
                        <p>Göttingen</p>
                        <p>Vandenhoeck & Ruprecht</p>
                        <p>1925</p>
                      </div>
                      <div className='flex flex-col p-2 m-2 text-xs uppercase'>
                        <p>Leipzig</p>
                        <p>J. C. Hinrichs'sche</p>
                        <p>Buchhandlung</p>
                      </div>
                    </div>
                    <div className='flex flex-col justify-center items-center text-center p-2 m-2 uppercase'>
                        <Link href="/ginza/introduction">
                          <button>
                            <p onClick={() => setPage(1)} className='bg-violet-300 rounded-xl w-fit p-2 m-2'>Introduction</p>
                          </button>
                        </Link>
                        <Link href="/ginza/rightpart">
                          <button>
                            <p className='bg-violet-300 rounded-xl w-fit p-2 m-2'>Right Part</p>
                          </button>
                        </Link>

                        <div className='flex flex-row flex-wrap'>
                          <Link href="/ginza/rightpart/book1">
                            <button>
                              <p className='font-bold hover:bg-violet-200 rounded-xl transition-all w-fit p-2 m-2'>Book 1</p>
                            </button>
                          </Link>
                          <Link href="/ginza/rightpart/book2">
                            <button>
                              <p className='font-bold hover:bg-violet-200 rounded-xl transition-all w-fit p-2 m-2'>Book 2</p>
                            </button>
                          </Link>
                        </div>
                       
                        <Link href="/">
                          <button>
                            <p className='bg-violet-300 rounded-xl w-fit p-2 m-2'>Left Part</p>
                          </button>
                        </Link>
                      </div>
                      <hr />
                  </div>
                  }
                  {language == 1 &&
                      <div>
                        <h3 className='text-2xl lg:text-4xl font-bold uppercase p-4 m-4'>GINZĀ</h3>
                        <h3 className='text-xl lg:text-3xl font-bold uppercase p-2 m-2'>DER SCHATZ</h3>
                        <p className='text-sm uppercase'>oder</p>
                        <h3 className='text-xl lg:text-3xl font-bold uppercase p-2 m-2'>DAS GROSSE BUCH DER MANDÄER</h3>
                        <p className='text-sm uppercase'>übersetzt und erklärt</p>
                        <p className='text-sm uppercase'>von</p>
                        <h3 className='text-xl lg:text-3xl font-bold uppercase p-2 m-2'>Mark Lidzbarski</h3>
                        <div className='flex flex-row flex-wrap text-center items-center justify-center p-2 m-2'>
                          <div className='flex flex-col p-2 m-2 text-xs uppercase'>
                            <p>Göttingen</p>
                            <p>Vandenhoeck & Ruprecht</p>
                            <p>1925</p>
                          </div>
                          <div className='flex flex-col p-2 m-2 text-xs uppercase'>
                            <p>Leipzig</p>
                            <p>J. C. Hinrichs'sche</p>
                            <p>Buchhandlung</p>
                          </div>
                        </div>
                          <div className='flex flex-col justify-center items-center text-center p-2 m-2 uppercase'>
                            <Link href="/ginza/introduction">
                              <button>
                                <p className='bg-violet-300 rounded-xl w-fit p-2 m-2'>Einleitung</p>
                              </button>
                            </Link>
                            <Link href="/ginza/rightpart">
                              <button>
                                <p className='bg-violet-300 rounded-xl w-fit p-2 m-2'>Rechter Teil</p>
                              </button>
                            </Link>
                            <Link href="/">
                              <button>
                                <p className='bg-violet-300 rounded-xl w-fit p-2 m-2'>Leiter Teil</p>
                              </button>
                            </Link>
                          </div>
                      </div>
                }
              </div>
        </div>
      </main>
    </>
  )
}
